
project_id = "bfmxxuarnqmxqqnpxqjf"

[api]
enabled = true
port = 54321
invaded_secret = "your-invaded-secret"

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false
port = 54327

[extensions.jwt]
secret = "your-jwt-secret"

[functions]
[functions.test-email-sending]
verify_jwt = true

[functions.send-lead-expiration-notification]
verify_jwt = false

[functions.send-lead-email-notification]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false
