
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfmxxuarnqmxqqnpxqjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmbXh4dWFybnFteHFxbnB4cWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTc4ODMsImV4cCI6MjA2MTY5Mzg4M30.MAQZ7I3pshciBJANhlPThK6XBxGemIPgflsMDz3OB_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with sessions enabled for persistence across page refreshes
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true, // Enable session persistence for production
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage // Explicitly use localStorage for token storage
    },
    global: {
      // Remove the custom header that's causing CORS issues
      // Increase default fetch timeout
      fetch: (url, options) => {
        return fetch(url, { 
          ...options, 
          signal: AbortSignal.timeout(15000) // 15 second timeout
        });
      }
    }
  }
);

// Add helper functions to safely handle data retrieval
export const getDataOrNull = <T>(response: { data: T | null, error: any }): T | null => {
  if (response.error) {
    console.error("Supabase query error:", response.error);
    return null;
  }
  return response.data;
};
